@startuml
package "core_persistence_local" {
object PersistenceLocalIO
object PersistenceLocalAdapter
PersistenceLocalIO --> PersistenceLocalAdapter
}

package "object_local" {
class CoreObjectLocalIO {}
}
package "object_local_ipml" {
'class ObjectLocalStore extends CoreObjectLocalIO {}
object ObjectLocalStore
ObjectLocalStore <- CoreObjectLocalIO
}

@enduml
