name: core_aggregate_e2e_tests_test_integration_core_aggregate_e2e_development
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  bloc:
  core_aggregate:
  core_aggregate_annotation:
  core_common:
  core_datastore:
  core_datastore_sembast:
  core_data:
  core_event_sourced:
  freezed_annotation:
  json_annotation: ^4.8.1
dev_dependencies:
  bloc_test:
  build_runner:
  checks:
  core_aggregate_build:
  freezed:
  json_serializable:
  lints:
  matcher:
  melos: ^3.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis:


index_generator:
  exclude:
    - '**.*.dart'
  indexes: []


dependency_overrides:
  core_aggregate:
    path: ../core_aggregate
  core_aggregate_annotation:
    path: ../core_aggregate_annotation
  core_aggregate_build:
    path: ../core_aggregate_build
  core_common:
    path: ../../core_common
  core_data:
    path: ../../core_data
  core_datastore:
    path: ../../core_datastore/core_datastore
  core_datastore_sembast:
    path: ../../core_datastore/core_datastore_sembast
  core_datastore_test:
    path: ../../core_datastore/core_datastore_test
  core_event_sourced:
    path: ../../core_event_sourced
