name: core_loco_data_test
version: 0.1.0+2
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  bloc:
  core_loco:
  core_loco_data:
  core_loco_test:
  freezed_annotation: ^2.2.0
  get_it:
  json_annotation:
  meta: ^1.9.1
  rxdart:


dev_dependencies:
  build_runner:
  freezed:
  glados:
  json_serializable:
  mocktail:
  test: ^1.21.0
  very_good_analysis: ^5.1.0

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Common libraries for core_platform
