targets:
  $default:
    dependencies:
      - core_persistence_remote_impl
      - core_persistence_remote_test
    builders:
      json_serializable:
        options:
          explicit_to_json: true
