targets:
  $default:
    dependencies:
      - core_object_base
      - core_object_local
      - core_object_remote
    builders:
      json_serializable:
        options:
          explicit_to_json: true
