include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - "**/__brick__/**"

linter:
  rules:
    always_use_package_imports: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    prefer_constructors_over_static_methods: false
    public_member_api_docs: false
    unnecessary_library_directive: false
