Here is the graph with the objects sorted alphabetically:

@startuml
object object_persistence   
object object_persistence_base
object object_persistence_local
object object_persistence_local_test
object object_persistence_remote
object object_persistence_remote_test 
object object_persistence_test


object_persistence --> object_persistence_remote


object_persistence_remote --> object_persistence_base


object_persistence_remote_test --> object_persistence_remote
object_persistence_remote_test <.. object_persistence_remote

object_persistence_test <-- object_persistence
object_persistence_test ..> object_persistence

object_persistence_test --> object_persistence_remote_test

object_persistence_local_test --> object_persistence_local

object_persistence_local_test <.. object_persistence_local

object_persistence --> object_persistence_local

object_persistence_local --> object_persistence_base

object_persistence_test --> object_persistence_local_test

@enduml
