name: flakka
description: distributed application toolkit
repository: https://github.com/bestow-code/flakka
version: 0.1.0-pre.1

environment:
  sdk: '>=3.0.5'
  flutter: ">=3.10.5"

dependencies:
  core_application:
  core_application_store:
  core_data:
  core_data_store:
  core_journal:
  core_journal_store:
  core_object:
  core_object_store:

#  core_aggregate:
  get_it:

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.21.0

index_generator:
  indexes: []
