name: core_common
version: 0.1.0+2
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  freezed_annotation: ^2.2.0
  meta: ^1.9.1

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: 5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Common libraries for core_platform
