name: core_common_impl
version: 0.1.0+2
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  bloc:
  core_common:
  freezed_annotation: ^2.2.0
  get_it:
  json_annotation:
  meta: ^1.9.1
  rxdart:

dev_dependencies:
  build_runner:
  core_common_test:
  freezed:
  json_serializable:
  test: ^1.21.0
  very_good_analysis: 5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Common libraries for core_platform
