name: core_aggregate_test
version: 0.1.0
description: Support libraries for defining Core Aggregates
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  bloc_test:
  core_aggregate:
  core_common:
  core_data:
  core_datastore:
  core_datastore_test:
  core_application:
  core_application_test:
  directed_graph: ^0.3.9
  freezed_annotation: ^2.2.0
  logging: ^1.2.0
  meta: ^1.9.1
  rxdart: ^0.27.7
dev_dependencies:
  build_runner: ^2.4.5
  dependency_validator: ^3.0.0
  freezed: ^2.3.5
  glados:
  json_serializable: ^6.7.0
  very_good_analysis: ^3.1.0
  test: ^1.24.4

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: structures and behavior for defining a core aggregate
