name: core_common_test
version: 0.1.0+2
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  bloc:
  core_common:
  core_common_impl:
  dart_random_choice:
  freezed_annotation: ^2.2.0
  get_it:
  glados:
  interleave:
  json_annotation:
  meta: ^1.9.1
  rxdart:


dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  mocktail:
  test: ^1.21.0
  very_good_analysis: ^5.1.0

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src/scaffolding
      name: core_common_test_scaffolding
    - path: lib
      include:
        - src/core
      docs: Common libraries for core_platform
      exports:
        - package: package:glados/glados.dart
#          show:
#            - Any
#            - ExploreConfig
#            - Glados
#            - Glados2
#            - Glados3
#            - Generator
#            - AnyUtils
#            - BigIntAnys
#            - BoolAny
#            - CombinableAny
#            - DateTimeAnys
#            - DoubleAnys
#            - DurationAnys
#            - GeneratorUtils
#            - IntAnys
#            - ListAnys
#            - MapAnys
#            - NullAny
#            - NumAnys
#            - RandomUtils
#            - SetAyns
#            - StringAnys
#            - any
#        - package: package:test/expect.dart
