name: core_common_test
version: 0.1.0+2
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.2.0

dependencies:
  bloc:
  core_common:
  dart_random_choice:
  freezed_annotation: ^2.2.0
  get_it:
  glados:
    git:
      url: https://github.com/bestow-code/glados
      path: glados
      ref: current
  interleave:
  json_annotation:
  meta: ^1.9.1
  rxdart:


dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  mocktail:
  test: ^1.21.0
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - name: scaffolding
      path: lib
      include:
        - src/scaffolding

    - path: lib
      include:
        - src/core
      docs: Common libraries for core_platform
      exports:
        - package: package:glados/glados.dart
          show:
            - Any
            - ExploreConfig
            - Glados
            - Glados2
            - Glados3
            - Generator
            - AnyUtils
            - BigIntAnys
            - BoolAny
            - CombinableAny
            - DateTimeAnys
            - DoubleAnys
            - DurationAnys
            - GeneratorUtils
            - IntAnys
            - ListAnys
            - MapAnys
            - NullAny
            - NumAnys
            - RandomUtils
            - SetAyns
            - StringAnys
            - any
        - package: package:test/expect.dart
