name: core_persistence_remote_tests
version: 0.1.1
publish_to: none
#description: A store for core platform's Entry
#repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  async: ^2.11.0
  collection:
  core_common: ^0.1.0+2
  core_object:
  core_persistence:
  core_persistence_base:
  core_persistence_base_impl:
  core_persistence_remote:
  core_persistence_remote_test:
  freezed_annotation: ^2.2.0
  get_it:
  glados:
  injectable:
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  rxdart:
  test:

dev_dependencies:
  build_runner:
  freezed:
  injectable_generator:
  json_serializable:
  matcher:
  mocktail: ^1.0.0
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Test kit for Core Entry Store implementations
