name: core_entry_store_firestore
version: 0.1.0+1
description: A Firestore adapter for core platform's Core Entry Store
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'
  flutter: '>=3.10.5'

dependencies:
  cloud_firestore: ^4.8.2
  collection: ^1.17.2
  core_common: ^0.1.0+2
  core_entry: ^0.1.1+1
  core_entry_store:  ^0.1.2
  firebase_core:  ^2.14.0
  flutter:
    sdk: flutter
  freezed_annotation:  ^2.2.0
  rxdart: ^0.27.7



dev_dependencies:
  build_runner:
  core_entry_store_test:
  freezed:
  integration_test:
    sdk: flutter
  json_serializable:
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Firestore adapter of Core Entry Store
