name: core_entry_store_firestore
version: 0.1.0+1
description: A Firestore adapter for core platform's Core Entry Store
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'
  flutter: '^3.10.5'

dependencies:
  cloud_firestore:
  collection:
  core_common:
  core_entry:
  core_entry_store:
  firebase_core:
  flutter:
    sdk: flutter
  freezed_annotation:
  rxdart:



dev_dependencies:
  build_runner:
  core_entry_store_test:
  freezed:
  integration_test:
    sdk: flutter
  json_serializable:
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Firestore adapter of Core Entry Store
