name: core_entry
version: 0.1.1+1
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  core_common: ^0.1.0+2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  test:
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Entry model and support
