name: core_object_store_sembast
version: 0.1.0-alpha.3
description: A store for core platform's Entry
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  core_common:
  core_object:
  core_object_store:
  get_it: ^7.6.0
  injectable: ^2.2.0
  meta: ^1.9.1
  rxdart: ^0.27.7
  sembast:

dev_dependencies:
  build_runner:
#  core_object_test:
  core_object_store_test:
  core_object_store_sembast_test:
  glados:
  injectable_generator: ^2.3.0
  mocktail: ^0.3.0
  test: ^1.24.4
  spec: ^0.2.3
  very_good_analysis: ^5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Fake for Core Entry Store
