targets:
  $default:
    dependencies:
      - core_object
      - core_object_remote_test
      - core_object_local_test
    builders:
      json_serializable:
        options:
          explicit_to_json: true
