name: core_aggregate_protoc_plugin
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-91.0.dev

# Add regular dependencies here.
dependencies:
  antlr4:
  build:
  built_value:
  built_collection:
  code_builder:
  either_dart:
  fixnum:
  path:
  protobuf:
  protoc_plugin:

dev_dependencies:
  build_runner:
  build_test:
  built_value_generator:
  lints: ^3.0.0
  test: ^1.24.0
