name: {{ package_name.snakeCase() }}
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  bloc:
  core_aggregate:
  core_aggregate_annotation:
  core_common:
  core_data_store:
  core_data_store_fake:
  core_event:
  core_event_sourced:
  freezed_annotation:
  json_annotation: ^4.8.1
dev_dependencies:
  bloc_test:
  build_runner:
  checks:
  core_aggregate_build:
  freezed:
  json_serializable:
  lints:
  matcher:
  melos: ^3.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis:


index_generator:
  exclude:
    - '**.*.dart'
  indexes: []


dependency_overrides:
  core_aggregate:
    path: {{{ packages_rel_path }}}../core_aggregate
  core_aggregate_annotation:
    path: {{{ packages_rel_path }}}../core_aggregate_annotation
  core_aggregate_build:
    path: {{{ packages_rel_path }}}../core_aggregate_build
  core_common:
    path: {{{ packages_rel_path }}}../../core_common
  core_data:
    path: {{{ packages_rel_path }}}../../core_data
  core_data_store:
    path: {{{ packages_rel_path }}}../../core_data_store/core_data_store
  core_data_store_fake:
    path: {{{ packages_rel_path }}}../../core_data_store/core_data_store_fake
  core_data_store_test:
    path: {{{ packages_rel_path }}}../../core_data_store/core_data_store_test
  core_event_sourced:
    path: {{{ packages_rel_path }}}../../core_event_sourced
