name: brick_validator
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  cli_script: ^0.3.1
  mason: ^0.1.0-dev.49
  path: ^1.8.3


dev_dependencies:
  dependency_validator: ^3.0.0
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
