name: core_datastore_test
version: 0.1.1
publish_to: none
#description: A store for core platform's Entry
#repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  async: ^2.11.0
  core_common: ^0.1.0+2
  core_data:
  core_datastore:
  core_entry:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  spec: ^0.2.3

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  matcher:
  mocktail: ^0.3.0
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Test kit for Core Entry Store implementations
