name: core_data_store
version: 0.1.2
description: A store for core platform's Entry
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  core_data:
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.7
dev_dependencies:
  build_runner: ^2.4.5
  build_verify: ^3.1.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Foundation for Core Entry Store
