name: core_journal_impl
version: 0.1.0-alpha.1
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.2.0

dependencies:
  bloc: ^8.1.2
  collection:
  core_common:
  core_data:
  core_data_impl:
  core_journal:
  core_object:
  directed_graph: ^0.3.9
  freezed_annotation: ^2.2.0
  meta: ^1.9.1
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test:
  build_runner:
  core_data_test:
#  core_journal_impl_test:
  core_journal_test:
  freezed: ^2.3.5
  core_common_test:
  json_serializable: ^6.7.0
  test: ^1.21.0
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Common libraries for core_platform
