name: core_aggregate_build
version: 0.1.0+1
description: Build support libraries for defining Core Aggregates
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  analyzer: 
  build: ^2.4.0
  code_builder: ^4.5.0
  collection: ^1.17.2
  core_aggregate_annotation: ^0.1.2
  freezed_annotation: ^2.2.0
  glob: ^2.1.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  path: ^1.8.3
  recase: ^4.1.0
  source_gen: ^1.3.2

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.7
  built_value_generator: ^8.6.1
  dependency_validator: ^3.0.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src/*/*.dart
    - path: lib/src/code_builder
    - path: lib/src/impl_descriptor_builder
    - path: lib/src/api_descriptor_builder
    - path: lib/src/common
