builders:
#  source_builder:
#    import: package:core_aggregate_build/core_aggregate_build.dart
#    builder_factories: ['SourceBuilder.from']
#    build_extensions: {'.dart':['.core.dart']}
#    auto_apply: root_package
#    runs_before: ["freezed:freezed"]
#    build_to: source
#    defaults:
#      generate_for:
#        - lib/src/**/*.dart
#    required_inputs:
#      - .root_impl.json
#      - .aggregate_impl.json
#      - .impl_component.json
#      - .root_api.json
#      - .aggregate_api.json
#      - .api_component.json
#
#  root_impl_builder:
#    import: package:core_aggregate_build/core_aggregate_build.dart
#    builder_factories: ['RootImplDescriptorBuilder.from']
#    build_extensions: {'.dart':['.root_impl.json']}
#    auto_apply: root_package
#    runs_before: ["freezed:freezed", 'source_builder']
#    build_to: cache
#    defaults:
#      generate_for:
#        - lib/src/**/*.dart
#    required_inputs:
#      - .root_impl.json
#      - .aggregate_impl.json
#      - .impl_component.json
#      - .root_api.json
#      - .aggregate_api.json
#      - .api_component.json
#
#  aggregate_impl_builder:
#    import: package:core_aggregate_build/core_aggregate_build.dart
#    builder_factories: ['AggregateImplDescriptorBuilder.from']
#    build_extensions: {'.dart':['.aggregate_impl.json']}
#    auto_apply: root_package
#    runs_before: ["freezed:freezed", 'root_impl_builder']
#    build_to: cache
#    defaults:
#      generate_for:
#        - lib/src/**/*.dart
#    required_inputs:
#      - .impl_component.json
#      - .aggregate_api.json
#
#  impl_component_builder:
#    import: package:core_aggregate_build/core_aggregate_build.dart
#    builder_factories: ['ImplComponentDescriptorBuilder.from']
#    build_extensions: {'.dart':['.impl_component.json']}
#    auto_apply: root_package
#    runs_before: ["freezed:freezed", 'aggregate_impl_builder']
#    build_to: cache
#    defaults:
#      generate_for:
#        - lib/src/**/*.dart
#
#  root_api_builder:
#    import: package:core_aggregate_build/core_aggregate_build.dart
#    builder_factories: ['RootApiDescriptorBuilder.from']
#    build_extensions: {'.dart':['.root_api.json']}
#    auto_apply: root_package
#    runs_before: ["freezed:freezed", 'root_impl_builder', 'source_builder']
#    build_to: cache
#    defaults:
#      generate_for:
#        - lib/src/**/*.dart
#    required_inputs:
#      - .aggregate_api.json
#
#  aggregate_api_builder:
#    import: package:core_aggregate_build/core_aggregate_build.dart
#    builder_factories: ['AggregateApiDescriptorBuilder.from']
#    build_extensions: {'.dart':['.aggregate_api.json']}
#    auto_apply: root_package
#    runs_before: ["freezed:freezed", 'root_api_builder', 'aggregate_impl_builder']
#    build_to: cache
#    defaults:
#      generate_for:
#        - lib/src/**/*.dart
#    required_inputs:
#      - .api_component.json
#
#  api_component_builder:
#    import: package:core_aggregate_build/core_aggregate_build.dart
#    builder_factories: ['ApiComponentDescriptorBuilder.from']
#    build_extensions: {'.dart':['.api_component.json']}
#    auto_apply: root_package
#    runs_before: ["freezed:freezed", 'aggregate_api_builder']
#    build_to: cache
#    defaults:
#      generate_for:
#        - lib/src/**/*.dart


targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
