name: core_persistence_base_impl
version: 0.1.2
description: A store for core platform's Entry
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  bloc:
  core_common:
  core_common_impl:
  core_persistence_base:
  freezed_annotation: ^2.2.0
  meta: ^1.9.1
  rxdart: ^0.27.7
dev_dependencies:
  build_runner: ^2.4.5
  build_verify: ^3.1.0
  freezed: ^2.3.5
  injectable_generator:
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Foundation for Core Entry Store
