name: core_entry_store_test
version: 0.1.1
description: A store for core platform's Entry
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  async: ^2.11.0
  core_common: ^0.1.0+2
  core_entry: ^0.1.1+1
  core_entry_store: ^0.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  test: ^1.24.3


dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  matcher:
  mocktail: ^0.3.0
  very_good_analysis:

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Test kit for Core Entry Store implementations
