targets:
  $default:
    dependencies:
      - core_object
      - core_object_remote_impl
      - core_object_local_impl
    builders:
      json_serializable:
        options:
          explicit_to_json: true
