name: core_data
version: 0.1.0-alpha.1
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  bloc: ^8.1.2
  core_common: ^0.1.0+2
  directed_graph: ^0.3.9
  freezed_annotation: ^2.2.0
  meta: ^1.9.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner:
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  test: ^1.21.0
  very_good_analysis: 5.0.0+1

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Common libraries for core_platform
