name: flakka_api
description: distributed application toolkit
repository: https://github.com/bestow-code/flakka
version: 0.1.0-pre.1

environment:
  sdk: '>=3.0.5'
  flutter: ">=3.10.5"

dependencies:
  analyzer:
  build:
  built_collection:
  built_value:
  code_builder:
  core_application:


#  core_aggregate:
  get_it: ^7.6.4

dev_dependencies:
  build_runner:
  built_value_generator:
  lints: ^3.0.0
  mocktail: ^1.0.0
  test: ^1.21.0

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      exports:
        - package: "package:core_application/core_application_api.dart"
#        - package: "package:core_application/core_application_api.dart"
