name: core_entry_store_test_util
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'
dependencies:
  core_entry:
  core_entry_store:
  async:
  bloc:
  bloc_concurrency:
  collection:
  debounce_throttle:
  directed_graph:
  freezed_annotation:
  json_annotation: ^4.8.0
  rxdart:
  logging:
  meta:
  test:
#  core_aggregate_test:
#  firebase_core:
#  cloud_firestore:
#  fake_cloud_firestore:
#  flutter:
#    sdk: flutter
#  integration_test:
#    sdk: flutter
#  flutter_test:
#    sdk: flutter

dev_dependencies:

  bloc_test:
  build_runner:
  lints: ^2.0.1
  freezed:
  json_serializable:
  matcher:
  mocktail: ^0.3.0
  melos: ^3.0.0
  very_good_analysis:
index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
