name: flakka
description: distributed application toolkit
repository: https://github.com/bestow-code/flakka
version: 0.1.0-pre.1

environment:
  sdk: '>=3.0.5'
  flutter: ">=3.10.5"

dependencies:
  core_application:
  core_application_impl:


#  core_aggregate:
  get_it: ^7.6.4

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.0
  test: ^1.21.0

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
