name: core_loco_test
version: 0.1.0+2
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  core_common_test:
  core_loco:
  freezed_annotation: ^2.2.0
  glados:
  meta: ^1.9.1
  rxdart:


dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  mocktail:
  test: ^1.21.0
  very_good_analysis: ^5.1.0

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      exclude:
        - src/scaffolding
      docs: Common libraries for core_platform

    - name: resource_scaffolding
      path: lib
      include:
        - src/scaffolding/resource_scaffolding.dart
