name: core_application
version: 0.1.0
description: structures and behavioral support for building event-sourced applications
repository: https://github.com/bestow-code/flakka

environment:
  sdk: '^3.0.5'

dependencies:
  async: ^2.11.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  collection: ^1.17.1
  core_common:
  core_data:
  core_journal:
  core_loco:
  core_persistence_base:
  debounce_throttle: ^2.0.0
  directed_graph: ^0.3.9
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  logging: ^1.2.0
  rxdart: ^0.27.7
  signals:

dev_dependencies:
  bloc_test:
  build_runner:
  core_application_test:
#  core_journal_impl_test:
#  core_object_impl_test:
  freezed:
  get_it:
  injectable:
  lints: ^3.0.0
  json_serializable:
  matcher:
  mocktail: ^1.0.0
  melos: ^3.0.0
  test:
  very_good_analysis:
index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      name: core_application_api
      include:
        - src/api
    - path: lib
      include:
        - src/base
    - path: lib
      name: core_application_impl
      include:
        - src/impl
