name: core_object_test
version: 0.1.0-alpha.1
description: Common libraries for flakka core platform
repository: https://github.com/bestow-code/flakka

environment:
  sdk: ^3.0.5

dependencies:
  core_common: ^0.1.0+2
  core_object:
  core_object_base_test:
  core_object_local_test:
  core_object_remote_test:
  core_persistence_base:
  freezed_annotation: ^2.2.0
  meta: ^1.9.1

dev_dependencies:
  build_runner:
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0

index_generator:
  exclude:
    - '**.*.dart'
  indexes:
    - path: lib
      include:
        - src
      docs: Common libraries for core_platform
      exports:
        - package: package:core_object_base_test/core_object_base_test.dart
        - package: package:core_object_local_test/core_object_local_test.dart
        - package: package:core_object_remote_test/core_object_remote_test.dart
        - package: package:core_persistence_test/core_persistence_test.dart
