name: core_entry_store_firebase

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
    paths:
      - packages/core_common/**
      - packages/core_entry/**
      - packages/core_entry_store/core_entry_store/**
      - packages/core_entry_store/core_entry_store_test/**
      - packages/core_entry_store/core_entry_store_firestore/**
      - .github/workflows/core_entry_firestore.yaml

jobs:
  verify_and_test:
    name: Verify and Test
    uses: ./.github/workflows/flutter_integration_package.yaml
    with:
      runs_on: self-hosted
      coverage_excludes: '**/*.g.dart **/*.freezed.dart'
      working_directory: packages/core_entry_store/core_entry_store_firestore
      flutter_channel: beta
      min_coverage: 0
      analyze_directories: "lib integration_test"
